export const SET_PUBLIC_KEY = 'SET_PUBLIC_KEY';
export const SET_PRIVATE_KEY = 'SET_PRIVATE_KEY';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const SET_IPV6 = 'SET_IPV6';
export const SET_CURRENT_IPV6 = 'SET_CURRENT_IPV6';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const SET_SHOW_IPV6_CHANGED_DIALOG = 'SET_SHOW_IPV6_CHANGED_DIALOG';