const {
  libraries: {
    React,
  },
  components: {
    Button,
    Panel,
    FieldSet,
  },
  utilities: {
    openInBrowser,
    showSuccessDialog,
    showInfoDialog,
  }
} = NEXUS;

const { useState } = React;

export default function ReferralPage() {
  const handleLoginWithModuleAuthorLink = () => {
    // Module author's referral link - proceeds support module development
    const moduleAuthorReferralLink = 'https://dex-trade.com/refcode/qj9c43';
    showInfoDialog({ 
      message: 'Opening Dex-Trade login. Using module author\'s referral ID - proceeds support module development.' 
    });
    openInBrowser(moduleAuthorReferralLink);
  };

  const handleGetMyReferralLink = () => {
    // Redirect to Dex-Trade referral program page where they can get their link
    const referralProgramUrl = 'https://dex-trade.com/account/referral';
    showInfoDialog({ 
      message: 'Opening Dex-Trade Referral Program page to get your personal referral link.' 
    });
    openInBrowser(referralProgramUrl);
  };

  return (
    <div style={{ padding: '20px', maxWidth: '800px', margin: 'auto auto' }}>
      <h2 style={{ marginBottom: '20px', color: '#00b7fa', textAlign: 'center' }}>Dex-Trade Referral Program</h2>
      
      {/* Referral Program Explanation */}
      <FieldSet legend="How the Referral Program Works" style={{ marginBottom: '20px' }}>
        <div style={{ padding: '15px', lineHeight: '1.6' }}>
          <p style={{ marginBottom: '15px' }}>
            Dex-Trade supports a 3-level referral system where you earn commissions 
            from trading fees generated by users you refer:
          </p>
          <ul style={{ marginLeft: '20px', marginBottom: '15px' }}>
            <li style={{ marginBottom: '8px' }}>
              <strong>Level 1:</strong> 10% commission from direct referrals
            </li>
            <li style={{ marginBottom: '8px' }}>
              <strong>Level 2:</strong> 7% commission from referrals of your referrals
            </li>
            <li style={{ marginBottom: '8px' }}>
              <strong>Level 3:</strong> 3% commission from third-level referrals
            </li>
          </ul>
          <p>
            Build your network and earn passive income from trading activity 
            across multiple levels of referrals!
          </p>
        </div>
      </FieldSet>

      {/* Login Section */}
      <FieldSet legend="Login to Dex-Trade" style={{ marginBottom: '20px' }}>
        <div style={{ padding: '15px', textAlign: 'center' }}>
          <p style={{ marginBottom: '15px', color: '#ccc' }}>
            Login using the module author's referral ID. Proceeds help support module development.
          </p>
          <Button
            skin="primary"
            onClick={handleLoginWithModuleAuthorLink}
            style={{ 
              padding: '12px 24px',
              fontSize: '16px',
              backgroundColor: '#00b7fa',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              color: 'black'
            }}
          >
            Login to Dex-Trade
          </Button>
          <p style={{ marginTop: '10px', fontSize: '12px', color: '#888' }}>
            * Uses module author's referral ID to support development
          </p>
        </div>
      </FieldSet>

      {/* Get Your Referral Link Section */}
      <FieldSet legend="Get Your Referral Link" style={{ marginBottom: '20px' }}>
        <div style={{ padding: '15px', textAlign: 'center' }}>
          <p style={{ marginBottom: '15px', color: '#ccc' }}>
            Access the Dex-Trade Referral Program page to get your personal referral link.
          </p>
          <Button
            skin="secondary"
            onClick={handleGetMyReferralLink}
            style={{ 
              padding: '12px 24px',
              fontSize: '16px',
              backgroundColor: 'transparent',
              border: '2px solid #666',
              borderRadius: '4px',
              cursor: 'pointer',
              color: '#ccc'
            }}
          >
            Get My Referral Link
          </Button>
        </div>
      </FieldSet>

      {/* Additional Info */}
      <div style={{ 
        padding: '15px', 
        backgroundColor: 'rgba(0, 183, 250, 0.1)', 
        borderRadius: '4px',
        border: '1px solid rgba(0, 183, 250, 0.3)'
      }}>
        <h4 style={{ color: '#00b7fa', marginBottom: '10px' }}>💡 How It Works</h4>
        <p style={{ color: '#ccc', fontSize: '14px', margin: 0 }}>
          The login button uses the module author's referral ID to help support continued 
          development of this module. Once you have your own referral link, you can share 
          it with others to start earning commissions from their trading activity.
        </p>
      </div>
    </div>
  );
}